@ECHO OFF
REM OpenXP "make" Batchdatei: Kompiliert alle fuer XP relevanten
REM Programme und Resourcen
REM Compiler ggf. als Kommandozeilenparameter uebergeben.

SET COMP=F:\PROGRA~1\BORLAN~1\BIN\BPC -OD -B
SET IHS=IHS
SET RC=RC

ECHO ON
%COMP% MAGGI
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% NDIFF
@IF ERRORLEVEL 1 GOTO FEHLER
REM %COMP% PMCONV
@IF ERRORLEVEL 1 GOTO FEHLER
REM %COMP% SCRIPTS
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% UUCICO
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% UUCP-FL1
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% UUZ
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% XP
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% XP-FM
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% XPME
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% YUP2PKT
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% ZFIDO
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% ZPR
@IF ERRORLEVEL 1 GOTO FEHLER
@
%RC% XP-D 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XP-E 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XPFM-D 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XPFM-E
@IF ERRORLEVEL 1 GOTO FEHLER
@
%IHS% XP 
@IF ERRORLEVEL 1 GOTO FEHLER
%IHS% XP-E
@IF ERRORLEVEL 1 GOTO FEHLER
:FEHLER
@ECHO OFF
