@ECHO OFF
REM OpenXP "make" Batchdatei: Kompiliert alle fuer XP relevanten
REM Programme und Resourcen
REM Compiler ggf. als Kommandozeilenparameter uebergeben.

SET TARGET=.\BUILD
SET COMP=D:\PROGRA~1\BP\BIN\BPC -CD -B -E%TARGET%

SET IHS=IHS
SET RC=RC

ECHO ON

%COMP% IHS
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% RC
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% DOCFORM
@IF ERRORLEVEL 1 GOTO FEHLER

MOVE Build\IHS.EXE DOC\IHS.EXE
MOVE Build\DOCFORM.EXE DOC\DOCFORM.EXE
MOVE Build\RC.EXE RC.EXE

%COMP% MAGGI
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% NDIFF
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% PMCONV
@IF ERRORLEVEL 1 GOTO FEHLER
REM %COMP% SCRIPTS
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% UUCICO
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% UUCP-FL1
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% UUZ
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% XP
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% XP-FM
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% XPME
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% YUP2PKT
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% ZFIDO
@IF ERRORLEVEL 1 GOTO FEHLER
%COMP% ZPR
@IF ERRORLEVEL 1 GOTO FEHLER
@
%RC% XP-D 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XP-E 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XPFM-D 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XPFM-E
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XPUU-D 
@IF ERRORLEVEL 1 GOTO FEHLER
%RC% XPUU-E
@IF ERRORLEVEL 1 GOTO FEHLER
MOVE *.RES Build\
@CD DOC
%IHS% XP 
@IF ERRORLEVEL 1 GOTO FEHLER
%IHS% XP-E
@IF ERRORLEVEL 1 GOTO FEHLER
@DEL IHS.EXE
@DEL DOCFORM.EXE
@CD ..
@CD Build
@DEL *.tpu
@CD ..
@DEL RC.EXE
:FEHLER
@ECHO OFF
