{$define HAVE_LIBNCURSES 1}
const CONF_PREFIX = '/usr/local';
const CONF_EXEC_PREFIX = '${prefix}';
const CONF_BINDIR = '${exec_prefix}/bin';
const CONF_SBINDIR = '${exec_prefix}/sbin';
const CONF_LIBEXECDIR = '${exec_prefix}/libexec';
const CONF_DATADIR = '${prefix}/share';
const CONF_SYSCONFDIR = '${prefix}/etc';
const CONF_SHAREDSTATEDIR = '${prefix}/com';
const CONF_LOCALSTATEDIR = '${prefix}/var';
const CONF_LIBDIR = '${exec_prefix}/lib';
const CONF_INCLUDEDIR = '${prefix}/include';
const CONF_OLDINCLUDEDIR = '/usr/include';
const CONF_INFODIR = '${prefix}/info';
const CONF_MANDIR = '${prefix}/man';
