program openxp;

{$I xpdefine.inc }

{%File 'maske.inc'}
{%File 'osdbsd.inc'}
{%File 'osddos32.inc'}
{%File 'osdlinux.inc'}
{%File 'osdos2.inc'}
{%File 'osdwin32.inc'}
{%File 'xp3o.inc'}
{%File 'xp4d.inc'}
{%File 'xp4w.inc'}
{%File 'xpconfigedit-servers.inc'}
{%File 'xpdefine.inc'}
{%File 'netcall\ncfido-emsi.inc'}
{%File 'netcall\ncfido-wazoo.inc'}
{%File 'netcall\ncfido-yoohoo.inc'}
{%File 'netcall\ncfido-binkp.inc'}
{%File 'ObjCOM\ocsdos.inc'}
{%File 'xpsendmessage_subs.inc'}

uses
	addresses in 'addresses.pas',
  addresslist in 'addresslist.pas',
  archive in 'archive.pas',
  charmaps in 'charmaps.pas',
  clip in 'clip.pas',
  CRC in 'crc.pas',
  database in 'database.pas',
  databaso in 'databaso.pas',
  datadef in 'datadef.pas',
  datadef1 in 'datadef1.pas',
  Debug in 'debug.pas',
  Direct in 'direct.pas',
  eddef in 'eddef.pas',
  editor in 'editor.pas',
  feiertag in 'feiertag.pas',
  fidoglob in 'fidoglob.pas',
  fileio in 'fileio.pas',
  help in 'help.pas',
  inout in 'inout.pas',
  IPAddr in 'ipaddr.pas',
  keys in 'keys.pas',
  lister in 'lister.pas',
  Log in 'log.pas',
  maske in 'maske.pas',
  maus2 in 'maus2.pas',
  MD5 in 'md5.pas',
  montage in 'montage.pas',
  mouse in 'mouse.pas',
  ndiff in 'ndiff.pas',
  ZFTools in 'zftools.pas',
  printerx in 'printerx.pas',
  ProgressOutput in 'progressoutput.pas',
  resource in 'resource.pas',
  stack in 'stack.pas',
  StringTools in 'stringtools.pas',
  Timer in 'timer.pas',
  typeform in 'typeform.pas',
  Unicode in 'unicode.pas',
  UTFTools in 'utftools.pas',
  viewer in 'viewer.pas',
  win2 in 'win2.pas',
  winxp in 'winxp.pas',
  xp_des in 'xp_des.pas',
  xp_iti in 'xp_iti.pas',
  xp_pgp in 'xp_pgp.pas',
  xp_uue in 'xp_uue.pas',
  xp0 in 'xp0.pas',
  xp1 in 'xp1.pas',
  xp10 in 'xp10.pas',
  xp1help in 'xp1help.pas',
  xp1input in 'xp1input.pas',
  xp1o in 'xp1o.pas',
  xp1o2 in 'xp1o2.pas',
  xp2 in 'xp2.pas',
  xp2c in 'xp2c.pas',
  xp2db in 'xp2db.pas',
  xp2f in 'xp2f.pas',
  xp3 in 'xp3.pas',
  xp3ex in 'xp3ex.pas',
  xp3o in 'xp3o.pas',
  xp3o2 in 'xp3o2.pas',
  xp4 in 'xp4.pas',
  xp4e in 'xp4e.pas',
  xp4o in 'xp4o.pas',
  xp4o2 in 'xp4o2.pas',
  xp4o3 in 'xp4o3.pas',
  xp5 in 'xp5.pas',
  xp8 in 'xp8.pas',
  xp9bp in 'xp9bp.pas',
  xpauto in 'xpauto.pas',
  xpcc in 'xpcc.pas',
  XPCfg in 'xpcfg.pas',
  xpconfig in 'xpconfig.pas',
  xpconfigedit in 'xpconfigedit.pas',
  xpdatum in 'xpdatum.pas',
  xpdiff in 'xpdiff.pas',
  xpe in 'xpe.pas',
  xpeasy in 'xpeasy.pas',
  xpf2 in 'xpf2.pas',
  xpfido in 'xpfido.pas',
  xpfidonl in 'xpfidonl.pas',
  xpftnadr in 'xpftnadr.pas',
  xpglobal in 'xpglobal.pas',
  xpheader in 'xpheader.pas',
  xpimpexp in 'xpimpexp.pas',
  xpkeys in 'xpkeys.pas',
  xpmakeheader in 'xpmakeheader.pas',
  xpmaus in 'xpmaus.pas',
  xpme in 'xpme.pas',
  xpmime in 'xpmime.pas',
  xpnt in 'xpnt.pas',
  XPProgressOutputWindow in 'xpprogressoutputwindow.pas',
  xpprogressoutputxy in 'xpprogressoutputxy.pas',
  xpreg in 'xpreg.pas',
  xpstat in 'xpstat.pas',
  xpterminal in 'xpterminal.pas',
  xpview in 'xpview.pas',
  xpx in 'xpx.pas',
  zcrfc in 'zcrfc.pas',
  OSDepend in 'osdepend.pas',
  SysUtils,
{$IFNDEF Kylix}
  xpcrt in 'xpcrt.pas',
  xpwin32 in 'xpwin32.pas',
  ZModem in 'netcall\zmodem.pas',
  ncgeneric in 'netcall\ncgeneric.pas',
  NCModem in 'netcall\ncmodem.pas',
  NCNNTP in 'netcall\ncnntp.pas',
  NCPOP3 in 'netcall\ncpop3.pas',
  NCSMTP in 'netcall\ncsmtp.pas',
  NCSocket in 'netcall\ncsocket.pas',
  ncuucp in 'netcall\ncuucp.pas',
  Netcall in 'netcall\netcall.pas',
  xpmodemscripts in 'netcall\xpmodemscripts.pas',
  xpncclient in 'netcall\xpncclient.pas',
  xpncfido in 'netcall\xpncfido.pas',
  xpncnntp in 'netcall\xpncnntp.pas',
  xpncpop3 in 'netcall\xpncpop3.pas',
  xpncuucp in 'netcall\xpncuucp.pas',
  ncuucp_e in 'netcall\ncuucp_e.pas',
  ncuucp_fz in 'netcall\ncuucp_fz.pas',
  ncuucp_g in 'netcall\ncuucp_g.pas',
  ncuucp_t in 'netcall\ncuucp_t.pas',
  xpnczconnect in 'netcall\xpnczconnect.pas',
  xpnetcall in 'netcall\xpnetcall.pas',
  ncfido in 'netcall\ncfido.pas',
  dos in 'delphi\dos.pas',
  objcom in 'ObjCOM\objcom.pas',
  Ringbuff in 'ObjCOM\ringbuff.pas',
{$ELSE}
  ZModem in 'netcall/zmodem.pas',
  ncgeneric in 'netcall/ncgeneric.pas',
  NCModem in 'netcall/ncmodem.pas',
  NCNNTP in 'netcall/ncnntp.pas',
  NCPOP3 in 'netcall/ncpop3.pas',
  NCSMTP in 'netcall/ncsmtp.pas',
  NCSocket in 'netcall/ncsocket.pas',
  ncuucp in 'netcall/ncuucp.pas',
  ncuucp_e in 'netcall/ncuucp_e.pas',
  ncuucp_fz in 'netcall/ncuucp_fz.pas',
  ncuucp_g in 'netcall/ncuucp_g.pas',
  ncuucp_t in 'netcall/ncuucp_t.pas',
  Netcall in 'netcall/netcall.pas',
  xpmodemscripts in 'netcall/xpmodemscripts.pas',
  xpncfido in 'netcall/xpncfido.pas',
  xpncnntp in 'netcall/xpncnntp.pas',
  xpncpop3 in 'netcall/xpncpop3.pas',
  xpncuucp in 'netcall/xpncuucp.pas',
  xpnczconnect in 'netcall/xpnczconnect.pas',
  xpnetcall in 'netcall/xpnetcall.pas',
  ncfido in 'netcall/ncfido.pas',
  dos in 'delphi/dos.pas',
  objcom in 'ObjCOM/objcom.pas',
  Ringbuff in 'ObjCOM/ringbuff.pas',
  ncursix in 'ncursix.pas',
{$ENDIF}
	xpserver in 'xpserver.pas',
  xpsendmessage_rta in 'xpsendmessage_rta.pas',
  xpsendmessage_internal in 'xpsendmessage_internal.pas',
  xpsendmessage in 'xpsendmessage.pas',
  RegExpr in 'regexpr.pas',
  main in 'main.pas',
  xpsendmessage_attach_analyze in 'xpsendmessage_attach_analyze.pas',
  markedlist in 'markedlist.pas',
  mime in 'mime.pas',
  mime_analyze in 'mime_analyze.pas',
  mime_base64 in 'mime_base64.pas',
  mime_qp in 'mime_qp.pas';

{$R *.res}

begin
  StartOpenXP;
end.

