K XP-FM v3.07 resource file
K Deutsch

# ----- Fehler in FIDO.CFG

100 Parameter-Fehler:~
101 InPath ungltig
102 MailPath fehlt
103 MailPath ungltig
104 Ungltiger Logfile-Name: %s
105 Datei fehlt:  %s
106 Name fehlt
107 'Address' fehlt
108 Ungltige / unvollst„ndige Adresse:  %s
109 ungltige Baudrate
110 Port-Adresse fehlt
111 IRQ-Nummer fehlt
112 InPath fehlt
113 Ungltige Baudrate
114 ungltige Tempor„rdatei
115 ZM.EXE fehlt
116 kein CTS-Signal
117 Fehler bei Portinitialisierung
118 'rz' fehlt (ZModem)
119 'sz' fehlt (ZModem)

# ----- Anwahl

160 abgebrochen
161 Modem initialisieren
162 w„hle %s (Versuch %s) ...
163 keine Verbindung
164 Modem auflegen
165 warte auf n„chsten Anruf ...
166 Anruf bei %s
167 Modem evtl. nicht aufgelegt?!

# ----- fehlerhaftes Carrier-Signal (Zeilenanzahl variabel):

+   170
1   FEHLER: Es ist ein Carrier-Signal auf COM%s vorhanden!
2
3   M”glicherweise haben Sie Ihr Modem falsch konfiguriert, sodaá
4   es ein Carrier-Signal liefert, obwohl gar keine Verbindung
5   besteht. Bitte berprfen Sie Ihre Modem-Einstellungen! N„heres
6   zum Carrier-Signal ist in Anhang F von XPOINT.TXT und in Ihrem
7   Modem-Handbuch beschrieben.
-
171 Taste drcken ...

# ----- Login-Handshake, XP-FM.INC

180 Hello-Sendefehler
181 Hello-Empfangsfehler
182 Handshake OK
183 korrigiere Uhrzeit
184 nicht implementiert
185 keine šbertragung m”glich :-(
186 fehlerhaftes EMSI-Paket erhalten
187 EMSI_NAK: wiederhole EMSI-Paket

# ----- Dateibertragung

190 tempor„re Zmodem-Parameterdatei
191 šbertragung abgebrochen
192 Senden
193 Empfangen
195 Carrier-Abbruch
