.TH OPENXP 1 "February 21, 2003"
.SH NAME
openxp \- Text-based mail and newsreader
.SH SYNOPSIS
.B openxp
.RI [ options ] 
.B ...
.SH "DESCRIPTION"
.B openxp
text-based messaging user agent based on
CrossPoint (XP) by Peter Mandrella.
.br
The full documentation can be found in 
.IR /usr/share/doc/openxp/ "."
.SH OPTIONS
A summary of options is included below.
Please not that the options don't follow the usual GNU command line syntax.
For a complete description, see the documentation 
.IR /usr/share/doc/openxp/ "."
.TP
.B /j
.R No silly message at program termination.
.\" kein dummer Spruch bei Programmende
.TP
.B /q
.R No bell.
.\" keine Tonsignale (quiet)
.TP
.B /ss
.R Activate screensaver.
.\" Screensaver aktivieren
.TP
.B /nolock  
.R Don't check lock files (dangerous).
.\" keine Überprüfung auf mehrfachen Programmstart
.TP
.B /trace   
.R Enable protocol for logon scripts.
.\" schaltet Script-Protokoll ein (XPOINT.TXT, Kap. 8.1)
.TP
.BI /dl: section = level
.RS
.RB Create ./debuglog.txt for 
.IB section "with level" level "."
.\" /dl:...  Debug-Logs (debuglog.txt) erzeugen, Parameter geben Grad der Ausführlichkeit an (z.B. "/dl:default=10")
.RE
.TP
.BI /k: X
.RS
.RI "Put key " X " into input buffer (to start key macros).
.\" /k:X     Taste X übergeben (für Tastenmakro)
.RE
.TP
.BI /pw: password
.RS
.RI "Use start password " password "."
.\" /pw:xx   Startpaßwort xx übergeben
.RE
.TP
.BI /z: lines
.RS
.RI "Set number of screen lines to " lines "."
.RE
.TP
.BI /l: language
.RS
.RI "Set language to " language "."
.\" /l:X     Sprache wählen (z.B. /l:D für deutsch)
.RE
.PP
.BI /n: server
.RI [ ":hh:mm" ]
.RS
.RI "Call " server " (at time " "hh:mm" ")."
.\" /n:BOX[:hh:mm]   Netcall bei BOX durchführen
.RE
.TP
.BI "/n:*"
.RS
.RI "Call all servers."
.\" /n:*             Netcall bei allen Boxen
.RE
.TP
.BI "/nr:" server
.RS
.RI "Call " server " via re-login."
.\" /nr:BOX          Relogin-Netcall bei BOX
.RE
.TP
.BI "/user:" server ":" username
.RS
.RI "Set own name to " username " for " server "."
.\" /user:BOX:NAME   Username bei BOX setzen
.RE
.TP
.BI "/ips:" server ":" bufferfile
.RS
.RI "Import " bufferfile " (must be ZConnect format) for sending via " server "."
.\" /ips:BOX:PUFFER  importiert und verschickt Pufferdatei
.RE
.TP
.BI "/autostart:" ...
.RS
.RI "Start at certain times (see documentation).
.\" /autostart:...   Programm zu bestimmten Uhrzeiten starten
.RE
.TP
.BI "/av:" archive-file
.RE
.RI "Start archive viewer for " archive-file "."
.SH AUTHOR
This manual page was written by Claus Färber <cl@openxp.de>,
for the Debian GNU/Linux system (but may be used by others).
