{ --------------------------------------------------------------- }
{ Dieser Quelltext ist urheberrechtlich geschuetzt.               }
{ (c) 1991-1999 Peter Mandrella                                   }
{ CrossPoint ist eine eingetragene Marke von Peter Mandrella.     }
{                                                                 }
{ Die Nutzungsbedingungen fuer diesen Quelltext finden Sie in der }
{ Datei SLIZENZ.TXT oder auf www.crosspoint.de/srclicense.html.   }
{ --------------------------------------------------------------- }
{ $Id$ }

{ linux/dosxh.inc 
  
  Zusaetzlicher Interface-Teil fuer die Unit DOSX }

uses
  xpglobal,
  linux;

{  ==================  Interface-Teil  ===================  }

{ Noch nichts vorhanden :-) }

{
	$Log$
	Revision 1.1  2000/06/29 12:55:38  hd
	- Linux-Teil isoliert

}
